# Generated by Django 3.2.13 on 2022-06-25 15:34

from django.db import migrations, models
import movies.models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='name',
            field=models.CharField(max_length=40, unique=True, validators=[movies.models.validate_string_processable]),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(default='', max_length=40, unique=True),
        ),
    ]
